version: 2

sources:
  - name: raw
    database: BFSI_DB
    schema: RAW
    tables:
      - name: RAW_CUSTOMERS
      - name: RAW_ACCOUNTS
      - name: RAW_TRANSACTIONS


models:
  - name: transaction_fct
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique

